apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pszw0rg6z-go
  janus-idp.io/tekton: pszw0rg6z-go
  backstage.io/kubernetes-id: pszw0rg6z-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: pszw0rg6z-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
